### ISSUE TITLE
[BUG] Obtain an error while trying to run test_protobuf code

### ISSUE THREAD

**Issue by Salonijain27** [dmlc/treelite#117]
```
In [1]: from __future__ import print_function
   ...: import unittest
   ...: import os
   ...: import numpy as np
   ...: import treelite
   ...: import treelite.runtime
   ...: from util import run_pipeline_test
   ...:
   ...: dpath = os.path.abspath(os.path.join(os.getcwd(), 'tests/examples/'))
   ...:
   ...: class TestProtobuf(unittest.TestCase):
   ...:   def test_round_trip(self):
   ...:     for model_format, model_path, dtest_path, libname_fmt, \
   ...:         expected_prob_path, expected_margin_path, multiclass in \
   ...:         [('xgboost', 'mushroom/mushroom.model', 'mushroom/agaricus.test',
   ...:           './agaricus{}', 'mushroom/agaricus.test.prob',
   ...:           'mushroom/agaricus.test.margin', False)]:
   ...:       model_path = os.path.join(dpath, model_path)
   ...:       model = treelite.Model.load(model_path, model_format=model_format)
   ...:       model.export_protobuf('./my.buffer')
   ...:       model2 = treelite.Model.load('./my.buffer', model_format='protobuf')
   ...:       for use_quantize in [False, True]:
   ...:         run_pipeline_test(model=model2, dtest_path=dtest_path,
   ...:                           libname_fmt=libname_fmt,
   ...:                           expected_prob_path=expected_prob_path,
   ...:                           expected_margin_path=expected_margin_path,
   ...:                           multiclass=multiclass, use_annotation=None,
   ...:                           use_quantize=use_quantize, use_parallel_comp=None)
   ...:
   ...: if __name__ == '__main__':
   ...:     unittest.main()
   ...:
E
======================================================================
ERROR: test_round_trip (__main__.TestProtobuf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-1-dfb34471b554>", line 20, in test_round_trip
    model.export_protobuf('./my.buffer')
  File "/home/nfs/saljain/pickle-rf/cuml/thirdparty/treelite/python/treelite/frontend.py", line 278, in export_protobuf
    _check_call(_LIB.TreeliteExportProtobufModel(c_str(filename), self.handle))
  File "/home/nfs/saljain/pickle-rf/cuml/thirdparty/treelite/python/treelite/core.py", line 50, in _check_call
    raise TreeliteError(_LIB.TreeliteGetLastError().decode('utf-8'))
treelite.common.util.TreeliteError: [14:22:40] /home/nfs/saljain/pickle-rf/cuml/thirdparty/treelite/src/frontend/protobuf.cc:342: Treelite was not compiled with Protobuf!

Stack trace returned 10 entries:
[bt] (0) /home/nfs/saljain/pickle-rf/cuml/thirdparty/treelite/python/treelite/libtreelite.so(dmlc::StackTrace[abi:cxx11]()+0x1bc) [0x7fcef44e31fc]
[bt] (1) /home/nfs/saljain/pickle-rf/cuml/thirdparty/treelite/python/treelite/libtreelite.so(treelite::frontend::ExportProtobufModel(char const*, treelite::Model const&)+0x2c6) [0x7fcef4559766]
[bt] (2) /home/nfs/saljain/pickle-rf/cuml/thirdparty/treelite/python/treelite/libtreelite.so(TreeliteExportProtobufModel+0x6) [0x7fcef44eb796]
[bt] (3) /home/nfs/saljain/miniconda3/envs/pickle-rf/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fcf8161c630]
[bt] (4) /home/nfs/saljain/miniconda3/envs/pickle-rf/lib/python3.7/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fcf8161bfed]
[bt] (5) /home/nfs/saljain/miniconda3/envs/pickle-rf/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fcf81632fce]
[bt] (6) /home/nfs/saljain/miniconda3/envs/pickle-rf/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so(+0x13a04) [0x7fcf81633a04]
[bt] (7) /home/nfs/saljain/miniconda3/envs/pickle-rf/bin/python(_PyObject_FastCallKeywords+0x3fb) [0x558f7ba0b16b]
[bt] (8) /home/nfs/saljain/miniconda3/envs/pickle-rf/bin/python(_PyEval_EvalFrameDefault+0x53ae) [0x558f7ba7049e]
[bt] (9) /home/nfs/saljain/miniconda3/envs/pickle-rf/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x558f7ba01cfb]



----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
An exception has occurred, use %tb to see the full traceback.

SystemExit: True

/home/nfs/saljain/miniconda3/envs/pickle-rf/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

**Comment by hcho3** [comment]
When you compile Treelite, you should elect to use Protobuf:
```
mkdir build
cd build
cmake .. -DENABLE_PROTOBUF=ON
make
```

**Comment by Salonijain27** [comment]
Thank you so much for the quick response.
