### ISSUE TITLE
BUG: Treelite unable to extract the correct information from an xgboost model 

### ISSUE THREAD

**Issue by Salonijain27** [dmlc/treelite#139]
After updating the xgboost version to `1.0.0dev.rapidsai0.12` , treelite is unable to extract the right information from it.
example code to reproduce this issue:
```
import os
import numpy as np
from sklearn.datasets import make_classification, make_regression
from sklearn.model_selection import train_test_split
from treelite import Model
import xgboost as xgb

def test_classification(n_rows, n_columns, num_rounds, tmp_path):
    # settings
    classification = True  # change this to false to use regression
    n_rows = n_rows  # we'll use 1 millions rows
    n_columns = n_columns
    n_categories = 2
    random_state = np.random.RandomState(43210)


    X, y = make_classification(n_samples=n_rows,
                               n_features=n_columns,
                               n_informative=int(n_columns/5),
                               n_classes=n_categories,
                               random_state=random_state)

    model_path = os.path.join(tmp_path, 'xgb_class.model')

    xgboost_params={}
    dtrain = xgb.DMatrix(X, label=y)
    # instantiate params
    params = {'silent': 1}
    # learning task params
    params['eval_metric'] = 'error'
    params['objective'] = 'binary:logistic'
    params['max_depth'] = 25
    params.update(xgboost_params)
    print("Params: ", params)
    bst = xgb.train(params, dtrain, num_rounds)
    bst.save_model(model_path)

    tl_model = Model.load(model_path, 'xgboost')
    print("tl_model num_feature: ", tl_model.num_feature)
    print("tl_model num_output_group: ", tl_model.num_output_group)
    assert tl_model.num_feature == n_columns
    assert tl_model.num_output_group == n_categories

if __name__ == '__main__':
    test_classification(1000, 20, 10, "./")
```

Output obtained:
```
Params:  {'silent': 1, 'eval_metric': 'error', 'objective': 'binary:logistic', 'max_depth': 25}
tl_model num_feature:  0
tl_model num_output_group:  0
Traceback (most recent call last):
  File "new_test.py", line 45, in <module>
    test_classification(1000, 20, 10, "./")
  File "new_test.py", line 41, in test_classification
    assert tl_model.num_feature == n_columns
AssertionError
```

**Comment by trivialfis** [comment]
Reproduced.  Will look into it.
