### ISSUE TITLE
import fails from virtual environment on Windows 10

### ISSUE THREAD

**Issue by AnotherSamWilson** [dmlc/treelite#388]
Virtual environment was created with `python -m venv testing`.
With this virtual environment activated, treelite was installed using `pip install treelite treelite_runtime`

When attempting to import treelite, I get this error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\swilson\virtual_environments\testing\lib\site-packages\treelite\__init__.py", line 7, in <module>
    from .frontend import Model, ModelBuilder
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\swilson\virtual_environments\testing\lib\site-packages\treelite\frontend.py", line 17, in <module>
    from .core import _LIB, c_array, _check_call
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\swilson\virtual_environments\testing\lib\site-packages\treelite\core.py", line 35, in <module>
    _LIB = _load_lib()
  File "C:\Users\swilson\virtual_environments\testing\lib\site-packages\treelite\core.py", line 18, in _load_lib
    os.add_dll_directory(os.path.join(os.path.normpath(sys.prefix), 'Library', 'bin'))
  File "C:\Users\swilson\AppData\Local\Programs\Python\Python39\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\swilson\\virtual_environments\\testing\\Library\\bin'
```

The python version of this virtual environment is 3.9.6. There is indeed no directory `C:\\Users\\swilson\\virtual_environments\\testing\\Library\\bin`, however there is a directory `C:\\Users\\swilson\\virtual_environments\\testing\\bin`. Should dlls be put directly into the `venv\bin` directory? I am not entirely sure how packaging dll with python packages works.

**Comment by hcho3** [comment]
On Windows, we recommend using Conda to manage virtual envs.
