### ISSUE TITLE
Killed when loading a xgboost model that has 500 trees

### ISSUE THREAD

**Issue by jiazou-bigdata** [dmlc/treelite#390]
We have successfully loaded a small xgboost model that has 10 trees into TreeLite. But we failed to load a large xgboost model that has 500 trees into TreeLite. 

```
Traceback (most recent call last):
  File "/home/ubuntu/netsdb/model-inference/decisionTree/experiments/test_treelite.py", line 15, in <module>
    convert(DATASET, CLASSIFIER, num_trees, depth)
  File "/home/ubuntu/netsdb/model-inference/decisionTree/experiments/convert_scikitlearn_to_treelite.py", line 18, in convert
    treelite_model.export_lib(toolchain=toolchain, libpath=libpath, verbose=True)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/treelite/frontend.py", line 213, in export_lib
    temp_libpath = create_shared(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/treelite/contrib/__init__.py", line 280, in create_shared
    _create_shared(dirpath, toolchain, recipe, nthread, options, verbose)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/treelite/contrib/gcc.py", line 43, in _create_shared
    return _create_shared_base(dirpath, recipe, nthread, verbose)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/treelite/contrib/util.py", line 130, in _create_shared_base
    raise TreeliteError('Error occured in worker #{}: '.format(tid) + \
treelite.util.TreeliteError: Error occured in worker #0: gcc: fatal error: Killed signal terminated program cc1
compilation terminated.
```

Below is the code that we used. Any suggestions?

```
import treelite
import treelite_runtime
import pickle
import xgboost
import gzip
import joblib
import pandas as pd
import treelite.sklearn
import os

def convert (DATASET, CLASSIFIER, num_trees, depth):
    model_path = os.path.join("models", DATASET+"_"+CLASSIFIER+"_"+str(num_trees)+"_"+str(depth)+".pkl")
    model = joblib.load(model_path)
    model.save_model("./model.model")
    treelite_model = treelite.Model.load("./model.model", model_format='xgboost')
    toolchain = 'gcc'
    libpath = os.path.join("models", DATASET+"_"+CLASSIFIER+"_"+str(num_trees)+"_"+str(depth)+"-1.so")
    treelite_model.export_lib(toolchain=toolchain, libpath=libpath, verbose=True)
```

**Comment by jiazou-bigdata** [comment]
After I set parallel_comp to be 4, which is the number of cores on my system, the compilation can finish. But it takes 10670.74 seconds time. Any suggestions to accelerate this process? Thanks.

**Comment by hcho3** [comment]
@jiazou-bigdata Try setting the following parameters when invoking `export_lib`:
```
treelite_model.export_lib(toolchain=toolchain, libpath=libpath, compiler="failsafe",
                          verbose=True, params={"dump_array_as_elf": 1})
```

**Comment by hcho3** [comment]
Alternatively, you can skip the compilation entirely by using `treelite.gtil.predict`:
```python
treelite.gtil.predict(treelite_model, data)
```

**Comment by jiazou-bigdata** [comment]
@hcho3 Thank you for your suggestion. It worked perfectly well.
