### ISSUE TITLE
[BUG]Model.from_xgboost

### ISSUE THREAD

**Issue by ysq151944** [dmlc/treelite#417]
Hi, I got TreeliteError when trying loading xgb model(xgb.__version__: 1.7.1, treelite.__version__: 3.0.0):

Traceback (most recent call last):
  File "C:\Anaconda3\envs\py310\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-6fa97ad3f01c>", line 1, in <cell line: 1>
    model = treelite.Model.from_xgboost(bst)
  File "C:\Anaconda3\envs\py310\lib\site-packages\treelite\frontend.py", line 388, in from_xgboost
    return cls.from_xgboost_json(model_json_str)
  File "C:\Anaconda3\envs\py310\lib\site-packages\treelite\frontend.py", line 436, in from_xgboost_json
    _check_call(_LIB.TreeliteLoadXGBoostJSONString(
  File "C:\Anaconda3\envs\py310\lib\site-packages\treelite\core.py", line 50, in _check_call
    raise TreeliteError(_LIB.TreeliteGetLastError().decode('utf-8'))
treelite.util.TreeliteError: [16:32:11] D:\a\1\s\src\frontend\xgboost_json.cc:539: Provided JSON could not be parsed as XGBoost model. Parsing error at offset 3276542: Terminate parsing due to Handler error.
ram":{"base_score":"5E-1","boost_from_average":"1","num_class":"0","num_feature":"87","num_target":"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


If the error could be solved by upgrading treelite version, then I got other problems:

1. the lastest versions of treelite and treelite-runtime are both 3.0.0(https://pypi.org/project/treelite/#history)

2. cannot download treelite-runtime 3.0.1 via conda(https://anaconda.org/conda-forge/treelite/files)

**Comment by hcho3** [comment]
The bug was fixed in Treelite 3.0.1. I will upload the package to PyPI shortly. For now, you can install Treelite 3.0.1 from Conda. (The runtime is already included if you install Treelite from Conda.)
