### ISSUE TITLE
Using clang toolkit on windows gives clang: error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msvc'

### ISSUE THREAD

**Issue by Naton1** [dmlc/treelite#432]
Here is my code loading an XGB model that gives me the following error:
```
x = treelite.Model.load(f'models/should-fill.model', 'xgboost')
x.export_lib(toolchain='clang', libpath=f'./models/should-fill.dll', verbose=True, params={'parallel_comp': 32})
```

```
[19:46:27] D:\bld\treelite_1674171529284\work\src\compiler\ast_native.cc:711: Using ASTNativeCompiler
[19:46:27] D:\bld\treelite_1674171529284\work\src\compiler\ast\split.cc:29: Parallel compilation enabled; member trees will be divided into 32 translation units.
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:92: Code generation finished. Writing code to files...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu2.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file main.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file header.h...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu5.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu0.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu1.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu3.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu4.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu6.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu7.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu8.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu9.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu10.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu11.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu12.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu13.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu14.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu15.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu16.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu17.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu18.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu19.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu20.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu21.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file recipe.json...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu22.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu23.c...
[19:46:27] D:\bld\treelite_1674171529284\work\src\c_api\c_api.cc:97: Writing file tu24.c...
[19:46:27] C:\Users\Nate\rl-ge\env\lib\site-packages\treelite\contrib\util.py:105: Compiling sources files in directory ./models\tmpwn3qpaae into object files (*.o)...
Traceback (most recent call last):
  File "C:\Users\Nate\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\223.8214.51\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "C:\Users\Nate\rl-ge\env\lib\site-packages\treelite\frontend.py", line 214, in export_lib
    temp_libpath = create_shared(
  File "C:\Users\Nate\rl-ge\env\lib\site-packages\treelite\contrib\__init__.py", line 280, in create_shared
    _create_shared(dirpath, toolchain, recipe, nthread, options, verbose)
  File "C:\Users\Nate\rl-ge\env\lib\site-packages\treelite\contrib\gcc.py", line 43, in _create_shared
    return _create_shared_base(dirpath, recipe, nthread, verbose)
  File "C:\Users\Nate\rl-ge\env\lib\site-packages\treelite\contrib\util.py", line 130, in _create_shared_base
    raise TreeliteError('Error occured in worker #{}: '.format(tid) + \
treelite.util.TreeliteError: Error occured in worker #0: Microsoft Windows [Version 10.0.19044.2486]
(c) Microsoft Corporation. All rights reserved.
(C:\Users\Nate\rl-ge\env) C:\Users\Nate\rl-ge>cd C:\Users\Nate\rl-ge\models\tmpwn3qpaae
(C:\Users\Nate\rl-ge\env) C:\Users\Nate\rl-ge\models\tmpwn3qpaae>type NUL > retcode_cpu0.txt
(C:\Users\Nate\rl-ge\env) C:\Users\Nate\rl-ge\models\tmpwn3qpaae>clang -c -O3 -o tu2.o tu2.c -fPIC -std=c99 -lm
clang: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
clang: error: unsupported option '-fPIC' for target 'x86_64-pc-windows-msvc'
(C:\Users\Nate\rl-ge\env) C:\Users\Nate\rl-ge\models\tmpwn3qpaae>echo %errorlevel% >> retcode_cpu0.txt
(C:\Users\Nate\rl-ge\env) C:\Users\Nate\rl-ge\models\tmpwn3qpaae>
```

I am using clang version 15.0.7 installed via conda-forge.

**Comment by hcho3** [comment]
Sorry we don't support clang on Windows
